// Generated by Apple Swift version 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import RealmSwift;
@import UIKit;
@import WebKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="DSCoreFramework",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

typedef SWIFT_ENUM(NSInteger, ActivityType, closed) {
  ActivityTypeToday = 0,
  ActivityTypeWeek = 1,
  ActivityTypeMonth = 2,
  ActivityTypeAbsolute = 3,
};

typedef SWIFT_ENUM(NSInteger, CampaignVariant, closed) {
  CampaignVariantAccess = 1,
  CampaignVariantBait = 2,
};

typedef SWIFT_ENUM(NSInteger, ConnectionType, closed) {
  ConnectionTypeHub = 0,
  ConnectionTypePersistent = 1,
};

typedef SWIFT_ENUM(NSInteger, DSCampaignVariant, closed) {
  DSCampaignVariantAccess = 1,
  DSCampaignVariantBait = 2,
};

typedef SWIFT_ENUM(NSInteger, DSErrors, closed) {
  DSErrorsDS_INVALID_SESSION = 0,
};

typedef SWIFT_ENUM(NSInteger, DSGenreType, closed) {
  DSGenreTypeNone = 0,
  DSGenreTypeFemale = 2,
  DSGenreTypeMale = 1,
};

typedef SWIFT_ENUM(NSInteger, DSLandingState, closed) {
  DSLandingStateSignout = -1,
  DSLandingStateSplash = 1,
  DSLandingStatePitch = 2,
  DSLandingStateLogin = 3,
  DSLandingStateTerms = 4,
  DSLandingStateCompleted = 5,
};

typedef SWIFT_ENUM(NSInteger, DSLoginType, closed) {
  DSLoginTypeAnonymous = 0,
  DSLoginTypeDriveSmart = 1,
  DSLoginTypeFacebook = 2,
  DSLoginTypeGoogle = 3,
};

@class DSRSmallAchievement;

SWIFT_CLASS("_TtC15DSCoreFramework14DSRAchievement")
@interface DSRAchievement : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nullable icon;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable subtitle;
@property (nonatomic, copy) NSString * _Nullable message;
@property (nonatomic, copy) NSString * _Nullable link;
@property (nonatomic, copy) NSString * _Nullable linkTitle;
@property (nonatomic, strong) DSRSmallAchievement * _Nullable next;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




SWIFT_CLASS("_TtC15DSCoreFramework13DSRAssistance")
@interface DSRAssistance : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nullable assistanceName;
@property (nonatomic, copy) NSString * _Nullable helpCallMisdn;
@property (nonatomic, copy) NSString * _Nullable panicCallMisdn;
@property (nonatomic, copy) NSString * _Nullable crashCallMisdn;
@property (nonatomic, copy) NSString * _Nullable assistanceIconPath;
@property (nonatomic, copy) NSString * _Nullable countryCode;
@property (nonatomic, copy) NSString * _Nullable backgroundLogo;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, DSRCampaignVariant, closed) {
  DSRCampaignVariantAccess = 1,
  DSRCampaignVariantBait = 2,
};


SWIFT_CLASS("_TtC15DSCoreFramework14DSRCertificate")
@interface DSRCertificate : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nullable certificateImage;
@property (nonatomic, copy) NSDate * _Nullable obtainCertificateDatetime;
@property (nonatomic, copy) NSString * _Nullable professionalBrandedUrl;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15DSCoreFramework9DSRDevice")
@interface DSRDevice : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nullable uuid;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
+ (NSArray<NSString *> * _Nonnull)indexedProperties SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, DSRGenreType, closed) {
  DSRGenreTypeNone = 0,
  DSRGenreTypeFemale = 2,
  DSRGenreTypeMale = 1,
};


SWIFT_CLASS("_TtC15DSCoreFramework22DSRHomeBiscuitActivity")
@interface DSRHomeBiscuitActivity : RealmSwiftObject
/// Start date: yyyy-MM-ddTHH:mm:ssZ
@property (nonatomic, copy) NSDate * _Nullable date;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15DSCoreFramework19DSRHomeBiscuitScore")
@interface DSRHomeBiscuitScore : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nullable icon;
@property (nonatomic, copy) NSString * _Nullable iconAbsolute;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15DSCoreFramework10DSRInsight")
@interface DSRInsight : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nullable message;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15DSCoreFramework11DSRInterest")
@interface DSRInterest : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nullable appIconPath;
@property (nonatomic, copy) NSString * _Nullable textDescription;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
+ (NSArray<NSString *> * _Nonnull)indexedProperties SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, DSRLandingState, closed) {
  DSRLandingStateSignout = -1,
  DSRLandingStateSplash = 1,
  DSRLandingStatePitch = 2,
  DSRLandingStateLogin = 3,
  DSRLandingStateTerms = 4,
  DSRLandingStateCompleted = 5,
};


SWIFT_CLASS("_TtC15DSCoreFramework11DSRLastTrip")
@interface DSRLastTrip : RealmSwiftObject
/// Distance in meters
@property (nonatomic) double distance;
@property (nonatomic) NSInteger incidents;
/// Start date: yyyy-MM-ddTHH:mm:ssZ
@property (nonatomic, copy) NSDate * _Nullable startDate;
/// End date: yyyy-MM-ddTHH:mm:ssZ
@property (nonatomic, copy) NSDate * _Nullable endDate;
@property (nonatomic) NSInteger score;
@property (nonatomic) NSInteger smartCoins;
@property (nonatomic, copy) NSString * _Nullable insights;
@property (nonatomic) NSInteger tripId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, DSRLoginType, closed) {
  DSRLoginTypeAnonymous = 0,
  DSRLoginTypeDriveSmart = 1,
  DSRLoginTypeFacebook = 2,
  DSRLoginTypeGoogle = 3,
};


SWIFT_CLASS("_TtC15DSCoreFramework13DSRMenuOption")
@interface DSRMenuOption : RealmSwiftObject
@property (nonatomic) NSInteger type;
@property (nonatomic, copy) NSString * _Nullable icon;
@property (nonatomic) NSInteger badge;
@property (nonatomic) BOOL isEnable;
@property (nonatomic) NSInteger position;
@property (nonatomic) NSInteger side;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, Option, closed) {
  OptionUserProfile = 0,
  OptionChallenges = 1,
  OptionTrophies = 2,
  OptionMyRewards = 3,
  OptionSmartCoins = 4,
  OptionPitStop = 5,
  OptionFindMyCar = 6,
  OptionFriends = 7,
  OptionShare = 8,
  OptionMyTrips = 9,
  OptionMyVehicle = 10,
  OptionMyMetrics = 11,
  OptionMyComments = 12,
  OptionHelp = 13,
  OptionSettings = 14,
  OptionMyResume = 15,
  OptionWallet = 16,
};


SWIFT_CLASS("_TtC15DSCoreFramework10DSRSetting")
@interface DSRSetting : RealmSwiftObject
@property (nonatomic) NSInteger idSetting;
@property (nonatomic) NSInteger group;
@property (nonatomic) NSInteger idMetric;
@property (nonatomic) NSInteger language;
@property (nonatomic, strong) DSRAssistance * _Nullable assistance;
@property (nonatomic) NSInteger idMap;
@property (nonatomic) NSInteger typeSetting;
@property (nonatomic, copy) NSDate * _Nullable reminder;
@property (nonatomic) NSInteger dateTimeFormat;
@property (nonatomic) NSInteger dateFormat;
@property (nonatomic) NSInteger timeFormat;
@property (nonatomic) NSInteger position;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
+ (NSArray<NSString *> * _Nonnull)indexedProperties SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, SettingType, closed) {
  SettingTypeLocation = 0,
  SettingTypeRealTime = 1,
  SettingTypeTermsAndConditions = 2,
  SettingTypeUnits = 3,
  SettingTypeLanguage = 4,
  SettingTypeAsisstance = 5,
  SettingTypeMapType = 6,
  SettingTypeFunFacts = 7,
  SettingTypeChallenges = 8,
  SettingTypeMetricsAlert = 9,
  SettingTypeSpecialOffers = 10,
  SettingTypeRewardAndCoupons = 11,
  SettingTypePitStop = 12,
  SettingTypeMonthlyReport = 13,
  SettingTypeNewsletter = 14,
  SettingTypeCountDown = 15,
  SettingTypeStartingTrip = 16,
  SettingTypeTripFinish = 17,
  SettingTypeReminder = 18,
  SettingTypeDateFormatType = 19,
  SettingTypeDateFormatDate = 20,
  SettingTypeDateFormatTime = 21,
  SettingTypeTripSummary = 22,
};

typedef SWIFT_ENUM(NSInteger, SettingGroupType, closed) {
  SettingGroupTypeNone = 0,
  SettingGroupTypeInAppDisplay = 1,
  SettingGroupTypeMail = 2,
  SettingGroupTypeAudio = 3,
  SettingGroupTypeReminder = 4,
};

typedef SWIFT_ENUM(NSInteger, SettingLanguageType, closed) {
  SettingLanguageTypeEnglish = 1,
  SettingLanguageTypeSpanish = 2,
  SettingLanguageTypeCatalan = 8,
  SettingLanguageTypeMexican = 150,
};

typedef SWIFT_ENUM(NSInteger, SettingUnit, closed) {
  SettingUnitMetric = 1,
  SettingUnitImperial = 2,
};

typedef SWIFT_ENUM(NSInteger, SettingMapType, closed) {
  SettingMapTypeNormal = 1,
  SettingMapTypeSatellite = 2,
  SettingMapTypeHybrid = 3,
  SettingMapTypeTerrain = 4,
};

typedef SWIFT_ENUM(NSInteger, SettingParentType, closed) {
  SettingParentTypePhone = 0,
  SettingParentTypeUser = 1,
  SettingParentTypeNotifications = 2,
  SettingParentTypeNotificationsAudio = 3,
  SettingParentTypeNone = 4,
};

typedef SWIFT_ENUM(NSInteger, SettingDateTimeFormat, closed) {
  SettingDateTimeFormatUserDefault = 1,
  SettingDateTimeFormatNotDefault = 2,
};

typedef SWIFT_ENUM(NSInteger, SettingDateFormat, closed) {
  SettingDateFormatDayFirst = 1,
  SettingDateFormatMonthFirst = 2,
};

typedef SWIFT_ENUM(NSInteger, SettingTimeFormat, closed) {
  SettingTimeFormatEuropean = 1,
  SettingTimeFormatUsa = 2,
};


/// Void sub class for realm storage
SWIFT_CLASS("_TtC15DSCoreFramework19DSRSmallAchievement")
@interface DSRSmallAchievement : DSRAchievement
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15DSCoreFramework12DSRSmartCoin")
@interface DSRSmartCoin : RealmSwiftObject
@property (nonatomic) NSInteger smartCoins;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15DSCoreFramework9DSRSmiles")
@interface DSRSmiles : RealmSwiftObject
@property (nonatomic) NSInteger nextLevel;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, DSRSmilesLevel, closed) {
  DSRSmilesLevelNormal = 1,
  DSRSmilesLevelBronze = 2,
  DSRSmilesLevelSilver = 3,
  DSRSmilesLevelGold = 4,
  DSRSmilesLevelComplete = 5,
};


SWIFT_CLASS("_TtC15DSCoreFramework13DSRTripDetail")
@interface DSRTripDetail : RealmSwiftObject
@property (nonatomic) NSInteger idTrip;
@property (nonatomic) NSInteger type;
@property (nonatomic, copy) NSString * _Nullable adressStart;
@property (nonatomic, copy) NSString * _Nullable adressFinish;
@property (nonatomic, copy) NSDate * _Nullable dateStart;
@property (nonatomic, copy) NSDate * _Nullable dateFinish;
@property (nonatomic, copy) NSString * _Nullable smileScore;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
+ (NSArray<NSString *> * _Nonnull)indexedProperties SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15DSCoreFramework7DSRUser")
@interface DSRUser : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable password;
@property (nonatomic, copy) NSString * _Nullable token;
@property (nonatomic, copy) NSString * _Nullable tokenSocial;
@property (nonatomic) NSInteger loginType;
@property (nonatomic) NSInteger landingStatus;
@property (nonatomic) NSInteger campaignVariant;
@property (nonatomic, copy) NSString * _Nullable language;
@property (nonatomic, copy) NSString * _Nullable assistantTel;
@property (nonatomic, copy) NSString * _Nullable assistantBackground;
@property (nonatomic, copy) NSString * _Nullable assistantLogo;
@property (nonatomic, copy) NSString * _Nullable userId;
@property (nonatomic, copy) NSString * _Nullable animationKey;
@property (nonatomic, copy) NSDate * _Nullable lastTripDate;
@property (nonatomic, copy) NSDate * _Nullable dateLogin;
@property (nonatomic, copy) NSString * _Nullable nameRegistrationCountry;
@property (nonatomic, copy) NSString * _Nullable apiKey;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
+ (NSArray<NSString *> * _Nonnull)indexedProperties SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15DSCoreFramework14DSRUserProfile")
@interface DSRUserProfile : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable surname;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable phone;
@property (nonatomic, copy) NSString * _Nullable codePhone;
@property (nonatomic, copy) NSString * _Nullable birthday;
@property (nonatomic) NSInteger genre;
@property (nonatomic, copy) NSString * _Nullable address;
@property (nonatomic, copy) NSString * _Nullable addressSecond;
@property (nonatomic, copy) NSString * _Nullable country;
@property (nonatomic, copy) NSString * _Nullable state;
@property (nonatomic, copy) NSString * _Nullable city;
@property (nonatomic, copy) NSString * _Nullable zipcode;
@property (nonatomic, copy) NSString * _Nullable memberCode;
@property (nonatomic, copy) NSString * _Nullable imageUrl;
@property (nonatomic, copy) NSString * _Nullable photo;
@property (nonatomic, copy) NSString * _Nullable plate;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
+ (NSArray<NSString *> * _Nonnull)indexedProperties SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum DSSignalTypes : NSInteger;
@class NSError;

SWIFT_PROTOCOL("_TtP15DSCoreFramework23DSSignalManagerProtocol_")
@protocol DSSignalManagerProtocol
@optional
- (void)onSignalReceivedWithType:(enum DSSignalTypes)type data:(id _Nullable)data;
- (void)invalidSessionWithError:(NSError * _Nonnull)error;
@end

typedef SWIFT_ENUM(NSInteger, DSSignalTypes, closed) {
  DSSignalTypesAchievements = 2,
  DSSignalTypesActivity = 3,
  DSSignalTypesScore = 4,
  DSSignalTypesLastTrip = 5,
  DSSignalTypesSmartcoins = 6,
  DSSignalTypesSmartmiles = 7,
  DSSignalTypesInsight = 9,
};

typedef SWIFT_ENUM(NSInteger, DSSmilesLevel, closed) {
  DSSmilesLevelNormal = 1,
  DSSmilesLevelBronze = 2,
  DSSmilesLevelSilver = 3,
  DSSmilesLevelGold = 4,
  DSSmilesLevelComplete = 5,
};



typedef SWIFT_ENUM(NSInteger, GenreType, closed) {
  GenreTypeNone = 0,
  GenreTypeFemale = 2,
  GenreTypeMale = 1,
};


SWIFT_CLASS("_TtC15DSCoreFramework3Hub")
@interface Hub : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, LandingState, closed) {
  LandingStateSignout = -1,
  LandingStateSplash = 1,
  LandingStatePitch = 2,
  LandingStateLogin = 3,
  LandingStateTerms = 4,
  LandingStateCompleted = 5,
};

typedef SWIFT_ENUM(NSInteger, LoginType, closed) {
  LoginTypeAnonymous = 0,
  LoginTypeDriveSmart = 1,
  LoginTypeFacebook = 2,
  LoginTypeGoogle = 3,
};

typedef SWIFT_ENUM(NSInteger, MenuSide, closed) {
  MenuSideLeft = 0,
  MenuSideRight = 1,
};



@class WKWebView;
@class WKNavigation;
@class WKUserContentController;
@class WKScriptMessage;
@class UIWebView;

SWIFT_CLASS("_TtC15DSCoreFramework7SignalR")
@interface SignalR : NSObject <UIWebViewDelegate, WKNavigationDelegate, WKScriptMessageHandler>
- (void)webView:(WKWebView * _Nonnull)webView didFinishNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)userContentController:(WKUserContentController * _Nonnull)userContentController didReceiveScriptMessage:(WKScriptMessage * _Nonnull)message;
- (BOOL)webView:(UIWebView * _Nonnull)webView shouldStartLoadWithRequest:(NSURLRequest * _Nonnull)request navigationType:(UIWebViewNavigationType)navigationType SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, SmilesLevel, closed) {
  SmilesLevelNormal = 1,
  SmilesLevelBronze = 2,
  SmilesLevelSilver = 3,
  SmilesLevelGold = 4,
  SmilesLevelComplete = 5,
};

typedef SWIFT_ENUM(NSInteger, State, closed) {
  StateConnecting = 0,
  StateConnected = 1,
  StateDisconnected = 2,
};

typedef SWIFT_ENUM(NSInteger, TripListType, closed) {
  TripListTypeProccesing = 0,
  TripListTypeScorable = 1,
  TripListTypeTestingTrip = 2,
  TripListTypeNoScorable = 3,
  TripListTypeNoGPS = 4,
};



#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
